name: Release to GitHub Container Registry

on:
  pull_request:
    branches:
      - main
    types:
      - opened
  push:
    tags:
      - 'v*' # Trigger on tags that start with 'v'

env:
  IMG: ghcr.io/remla2024-team14/model-serving:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract version
      id: version
      run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/tags/})"


    - name: Build Docker image
      run: docker build -t model-serve .

    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag Docker image
      run: docker tag model-serve ${{ env.IMG }}

    - name: Push Docker image to GitHub Container Registry
      run: docker push ${{ env.IMG }}

    - name: Trigger release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: Release ${{ steps.version.outputs.version }}
        body: |
          Release model inference server
