name: Release to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t model-serve .

    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag Docker image
      run: |
        IMG="ghcr.io/remla2024-team14/model-serving:latest"
        docker tag model-serve $IMG

    - name: Push Docker image to GitHub Container Registry
      run: docker push --all-tags $IMG

    - name: Trigger release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release model inference server
